steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/clima-cep', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/clima-cep']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'clima-cep'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clima-cep'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'WEATHER_API_KEY=${_WEATHER_API_KEY}'

substitutions:
  _WEATHER_API_KEY: '1c4ec0f2d6584342aea233704243010'

images:
  - 'gcr.io/$PROJECT_ID/clima-cep'
